# -*- coding: utf-8 -*-
"""final-rag5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WQ7uKe9GhQSeHrZ4EOo--eDScRKX4gp
"""

!pip uninstall -y langchain langchain-core langchain-community langchain-classic langchain-groq langchain-chroma langchain-huggingface chromadb

!pip install \
langchain==0.3.27 \
langchain-community==0.3.27 \
langchain-core==0.3.72 \
langchain-groq \
langchain-huggingface \
langchain-chroma \
chromadb

pip install pypdf

import chromadb
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma



loader = PyPDFLoader('python-ai.pdf')
docs = loader.load()

import re

def clean_text(text):
    # Join words split by hyphens at line breaks
    text = re.sub(r"-\n", "", text)

    # Replace single newlines with spaces
    text = re.sub(r"\n", " ", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()
for doc in docs:
    doc.page_content = clean_text(doc.page_content)

print(docs[10].page_content[:1000])

splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)
texts = splitter.split_documents(docs)


from langchain_huggingface import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

collection_name = "my_rag_collection"


client = chromadb.Client()
print("Initialized in-memory ChromaDB client.")

try:


    _ = client.get_or_create_collection(name=collection_name)
    print(f"ChromaDB native client successfully got or created collection '{collection_name}' (in-memory).")
except Exception as e:
    raise RuntimeError(f"Failed to create/get ChromaDB collection with native client: {e}. This is unexpected for an in-memory client.") from e


vectorstore = Chroma(
    client=client,
    collection_name=collection_name,
    embedding_function=embeddings,
    create_collection_if_not_exists=False
)



vectorstore.add_documents(documents=texts)

from google.colab import userdata

groq_api_key = userdata.get("groq-api-key")
print("API Loaded Successfully!" if groq_api_key else "API Not Found")
from langchain_groq import ChatGroq

llm = ChatGroq(
    groq_api_key=groq_api_key,
    model_name="llama-3.3-70b-versatile",
    temperature=0)

retriever = vectorstore.as_retriever(
    search_kwargs={"k": 3}
)

import langchain
print(langchain.__version__)

from langchain.chains import RetrievalQA

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    chain_type="stuff",
    return_source_documents=True
)

query = "What is Python?"

response = qa_chain.invoke({"query": query})

print(response["result"])

import gradio as gr

def chat(question):
    response = qa_chain.invoke({"query": question})
    return response["result"]

demo = gr.Interface(
    fn=chat,
    inputs=gr.Textbox(lines=2, placeholder="Ask anything about the PDF..."),
    outputs="text",
    title="PDF RAG Chatbot"
)

demo.launch()